### ISSUE TITLE
Serverless Toolbox Videos

### ISSUE THREAD

**Issue by mdnaseemashraf** [momander/serverlesstoolbox#24]
@momander Any chance we can get a remade playlist for the Serverless Toolbox video playlist in the future? I understand it's removal, but are there any plans for remaking those?

I'm trying to build a serverless REST API on GCP but, I'm at a loss of direction or documentation. Any help/direction is appreciated.

**Comment by momander** [comment]
Happy to hear that these videos were useful to you! You can find the new videos at http://goo.gle/ServerlessExpeditions. The new code repo is at https://github.com/GoogleCloudPlatform/serverless-expeditions
